"use client"

import { useState, useMemo, useRef, useEffect } from "react"
import { Shield, Users, Calendar, User, FileText, Upload, Plus, Search, Loader2, Check, X, AlertCircle } from "lucide-react"
import { api } from "@/lib/trpc/client"
import { toast } from "sonner"
import { useSession } from "next-auth/react"
import { format } from "date-fns"
import { id } from "date-fns/locale"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export default function InputDataPoinPage() {
  const { data: session } = useSession()
  const utils = api.useUtils()

  const [activeTab, setActiveTab] = useState<"input" | "rekap" | "menunggu">("input")
  const [wajibValidasiBk, setWajibValidasiBk] = useState(true)

  // ── Tab 1: Input Poin State ──
  const [jenisPoin, setJenisPoin] = useState<"negatif" | "positif">("negatif")
  const [subKategori, setSubKategori] = useState<string>("Ringan")
  const [selectedKategoriId, setSelectedKategoriId] = useState("")
  const [selectedSiswaIds, setSelectedSiswaIds] = useState<string[]>([])
  const [tanggalKejadian, setTanggalKejadian] = useState(() => {
    const tzoffset = (new Date()).getTimezoneOffset() * 60000
    return (new Date(Date.now() - tzoffset)).toISOString().slice(0, 16)
  })
  const [kronologi, setKronologi] = useState("")
  const [siswaSearchInput, setSiswaSearchInput] = useState("")
  const [showSiswaDropdown, setShowSiswaDropdown] = useState(false)
  const dropdownRef = useRef<HTMLDivElement>(null)

  // ── Tab 2: Rekap State ──
  const [searchRekapQuery, setSearchRekapQuery] = useState("")
  const [filterRekapJenis, setFilterRekapJenis] = useState<string>("all")

  // ── Database Queries & Mutations ──
  const { data: siswaList } = api.siswa.getAll.useQuery({ limit: 1000 })
  const { data: kategoriList, isLoading: isLoadingKategori } = api.poin.getAllKategori.useQuery({ aktifOnly: true })
  const { data: aturanList } = api.poin.getAllAturan.useQuery()
  const { data: daftarKelas } = api.kelas.getAll.useQuery({})
  const { data: riwayatSikap, isLoading: isLoadingRiwayat } = api.poin.getAllSikap.useQuery({ limit: 150 })

  // Click outside to close student dropdown
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
        setShowSiswaDropdown(false)
      }
    }
    document.addEventListener("mousedown", handleClickOutside)
    return () => document.removeEventListener("mousedown", handleClickOutside)
  }, [])

  const createSikapMutation = api.poin.createSikap.useMutation({
    onSuccess: (res) => {
      toast.success(`Berhasil mencatat poin sikap untuk ${res?.count || selectedSiswaIds.length} siswa`)
      utils.poin.getAllSikap.invalidate()
      utils.poin.getDashboardGuruAdmin.invalidate()
      utils.poin.getMonitoringThreshold.invalidate()
      // reset form
      setSelectedKategoriId("")
      setSelectedSiswaIds([])
      setKronologi("")
    },
    onError: (err) => {
      toast.error(err.message || "Gagal mencatat poin sikap")
    }
  })

  // Filter categories based on jenis & sub-category prefix brackets on client side
  const filteredKategori = useMemo(() => {
    if (!kategoriList) return []
    return kategoriList.filter((kat) => {
      if (kat.jenis !== jenisPoin) return false
      const subMatch = kat.nama.match(/^\[(.*?)\]/)
      const sub = subMatch ? subMatch[1] : ""
      return sub.toLowerCase() === subKategori.toLowerCase()
    })
  }, [kategoriList, jenisPoin, subKategori])

  const siswaKelasMap = useMemo(() => {
    if (!siswaList || !daftarKelas) return new Map<string, string>()
    const map = new Map<string, string>()
    siswaList.forEach((s: any) => { if (s.kelasId) map.set(s.id, s.kelasId) })
    return map
  }, [siswaList, daftarKelas])

  const kelasNameMap = useMemo(() => {
    if (!daftarKelas) return new Map<string, string>()
    const map = new Map<string, string>()
    daftarKelas.forEach((k: any) => { map.set(k.id, k.namaKelas) })
    return map
  }, [daftarKelas])

  const getKelasNama = (siswaId: string) => {
    const kelasId = siswaKelasMap.get(siswaId)
    if (!kelasId) return "-"
    return kelasNameMap.get(kelasId) || kelasId
  }

  // Get active category object
  const activeKategori = useMemo(() => {
    return kategoriList?.find(k => k.id === selectedKategoriId)
  }, [kategoriList, selectedKategoriId])

  // Auto-generate Action / Sanksi based on point rules
  const autoGeneratedAction = useMemo(() => {
    if (!activeKategori || !aturanList) return "Akan otomatis terisi sesuai pilihan jenis sikap/pelanggaran..."
    const pts = activeKategori.poin
    const matched = aturanList.find(rule => pts >= rule.poinMin && pts <= rule.poinMax)
    return matched ? `${matched.tindakLanjut} (Status: ${matched.status})` : "Tindakan BK Standard"
  }, [activeKategori, aturanList])

  // Search students
  const filteredSiswaSearch = useMemo(() => {
    if (!siswaList) return []
    const q = siswaSearchInput.toLowerCase().trim()
    if (!q) return siswaList.slice(0, 10)
    return siswaList.filter(s =>
      s.namaLengkap.toLowerCase().includes(q) ||
      (s.nisn && s.nisn.includes(q))
    ).slice(0, 15)
  }, [siswaList, siswaSearchInput])

  // Toggle student selection
  const handleToggleSiswa = (siswaId: string) => {
    setSelectedSiswaIds(prev =>
      prev.includes(siswaId) ? prev.filter(id => id !== siswaId) : [...prev, siswaId]
    )
  }

  // Handle Form Submission
  const handleSubmitPoin = (e: React.FormEvent) => {
    e.preventDefault()
    if (selectedSiswaIds.length === 0) {
      toast.error("Pilih minimal 1 siswa terlebih dahulu")
      return
    }
    if (!selectedKategoriId) {
      toast.error("Pilih jenis sikap / perilaku terlebih dahulu")
      return
    }

    createSikapMutation.mutate({
      siswaIds: selectedSiswaIds,
      kategoriId: selectedKategoriId,
      deskripsi: kronologi,
    })
  }

  // ── Tab 3: Menunggu Validasi BK ──
  const pendingLogs = useMemo(() => {
    if (!riwayatSikap) return []
    return riwayatSikap.filter((r: any) => r.status === "belum_diproses")
  }, [riwayatSikap])

  const approveMutation = api.poin.updateStatusMonitoring.useMutation({
    onSuccess: () => {
      toast.success("Poin berhasil divalidasi dan disetujui")
      utils.poin.getAllSikap.invalidate()
    },
    onError: (err) => toast.error(err.message || "Gagal memvalidasi poin")
  })

  const rejectMutation = api.poin.removeSikap.useMutation({
    onSuccess: () => {
      toast.success("Poin ditolak dan dihapus")
      utils.poin.getAllSikap.invalidate()
    },
    onError: (err) => toast.error(err.message || "Gagal menolak poin")
  })
  const filteredRekapList = useMemo(() => {
    if (!riwayatSikap) return []
    let list = riwayatSikap
    if (filterRekapJenis !== "all") {
      list = list.filter((r: any) => r.kategori?.jenis === filterRekapJenis)
    }
    if (searchRekapQuery.trim()) {
      const q = searchRekapQuery.toLowerCase()
      list = list.filter((r: any) =>
        r.siswa?.namaLengkap?.toLowerCase().includes(q) ||
        r.kategori?.nama?.toLowerCase().includes(q) ||
        r.guru?.namaLengkap?.toLowerCase().includes(q)
      )
    }
    return list
  }, [riwayatSikap, filterRekapJenis, searchRekapQuery])

  return (
    <div className="space-y-6 text-left">
      {/* Header Panel */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-2xl bg-teal-500/10 text-teal-650 flex items-center justify-center">
            <Plus size={20} className="stroke-[2.5]" />
          </div>
          <div>
            <h1 className="text-xl font-black text-slate-800 tracking-tight uppercase">Input & Data Poin</h1>
            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">
              Pencatatan Pelanggaran / Prestasi Sikap dan Rekap Log Siswa
            </p>
          </div>
        </div>
      </div>

      {/* Tabs Layout */}
      <div className="flex items-center gap-1 border-b border-slate-100">
        <button
          onClick={() => setActiveTab("input")}
          className={`px-5 py-3 text-xs font-black uppercase tracking-wider transition-all border-b-2 relative cursor-pointer ${
            activeTab === "input"
              ? "border-teal-500 text-teal-650"
              : "border-transparent text-slate-450 hover:text-slate-700"
          }`}
        >
          <div className="flex items-center gap-1.5">
            <Plus size={14} />
            <span>Input Poin</span>
          </div>
        </button>
        <button
          onClick={() => setActiveTab("rekap")}
          className={`px-5 py-3 text-xs font-black uppercase tracking-wider transition-all border-b-2 relative cursor-pointer ${
            activeTab === "rekap"
              ? "border-teal-500 text-teal-650"
              : "border-transparent text-slate-450 hover:text-slate-700"
          }`}
        >
          <div className="flex items-center gap-1.5">
            <FileText size={14} />
            <span>Rekap Poin & Tindak Lanjut</span>
          </div>
        </button>
        {wajibValidasiBk && (
          <button
            onClick={() => setActiveTab("menunggu")}
            className={`px-5 py-3 text-xs font-black uppercase tracking-wider transition-all border-b-2 relative cursor-pointer ${
              activeTab === "menunggu"
                ? "border-amber-500 text-amber-600"
                : "border-transparent text-slate-450 hover:text-slate-700"
            }`}
          >
            <div className="flex items-center gap-1.5">
              <AlertCircle size={14} />
              <span>Menunggu Validasi BK</span>
              {pendingLogs.length > 0 && (
                <span className="ml-1 bg-amber-100 text-amber-700 py-0.5 px-2 rounded-full text-[9px] font-black">
                  {pendingLogs.length}
                </span>
              )}
            </div>
          </button>
        )}
      </div>

      {/* Content Tabs */}
      {activeTab === "input" ? (
        <div className="neumo-card bg-background rounded-3xl p-6 space-y-6">
          <div>
            <h3 className="text-sm font-black text-slate-800 uppercase tracking-wider">Form Input Poin</h3>
            <p className="text-[10px] text-slate-400 font-bold uppercase mt-1">Catat pelanggaran atau prestasi siswa baru.</p>
          </div>

          <form onSubmit={handleSubmitPoin} className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Left Column Fields */}
            <div className="space-y-4">
              {/* Kategori Poin Switch */}
              <div>
                <label className="block text-[9px] font-black text-slate-455 uppercase tracking-widest mb-1.5">
                  Kategori Poin
                </label>
                <div className="grid grid-cols-2 gap-2">
                  <button
                    type="button"
                    onClick={() => {
                      setJenisPoin("negatif")
                      setSubKategori("Ringan")
                      setSelectedKategoriId("")
                    }}
                    className={`py-3 rounded-xl border text-xs font-black uppercase tracking-wider transition-all cursor-pointer ${
                      jenisPoin === "negatif"
                        ? "bg-rose-50 border-rose-200 text-rose-600 shadow-sm"
                        : "bg-slate-50 border-slate-200/50 text-slate-550 hover:bg-slate-100"
                    }`}
                  >
                    Pelanggaran (Negatif)
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setJenisPoin("positif")
                      setSubKategori("Akademik")
                      setSelectedKategoriId("")
                    }}
                    className={`py-3 rounded-xl border text-xs font-black uppercase tracking-wider transition-all cursor-pointer ${
                      jenisPoin === "positif"
                        ? "bg-emerald-50 border-emerald-200 text-emerald-600 shadow-sm"
                        : "bg-slate-50 border-slate-200/50 text-slate-550 hover:bg-slate-100"
                    }`}
                  >
                    Prestasi (Positif)
                  </button>
                </div>
              </div>

              {/* Sub Kategori / Bidang */}
              <div>
                <label className="block text-[9px] font-black text-slate-455 uppercase tracking-widest mb-1.5">
                  Sub-Kategori / Bidang
                </label>
                <div className="flex flex-wrap gap-2">
                  {jenisPoin === "negatif" ? (
                    ["Ringan", "Sedang", "Berat"].map((sk) => (
                      <button
                        key={sk}
                        type="button"
                        onClick={() => { setSubKategori(sk); setSelectedKategoriId("") }}
                        className={`px-4 py-2.5 rounded-xl border text-[10px] font-black uppercase tracking-wider transition-all cursor-pointer ${
                          subKategori === sk
                            ? "bg-rose-50/50 border-rose-200 text-rose-600 shadow-xs"
                            : "bg-slate-50/30 border-slate-200/30 text-slate-550 hover:bg-slate-50"
                        }`}
                      >
                        {sk}
                      </button>
                    ))
                  ) : (
                    ["Akademik", "Non Akademik", "Kontribusi", "Keaktifan"].map((sk) => (
                      <button
                        key={sk}
                        type="button"
                        onClick={() => { setSubKategori(sk); setSelectedKategoriId("") }}
                        className={`px-4 py-2.5 rounded-xl border text-[10px] font-black uppercase tracking-wider transition-all cursor-pointer ${
                          subKategori === sk
                            ? "bg-emerald-50/50 border-emerald-200 text-emerald-600 shadow-xs"
                            : "bg-slate-50/30 border-slate-200/30 text-slate-550 hover:bg-slate-50"
                        }`}
                      >
                        {sk}
                      </button>
                    ))
                  )}
                </div>
              </div>

              {/* Jenis Sikap / Perilaku */}
              <div>
                <label className="block text-[9px] font-black text-slate-455 uppercase tracking-widest mb-1.5">
                  Jenis Sikap / Perilaku <span className="text-rose-500">*</span>
                </label>
                <select
                  required
                  value={selectedKategoriId}
                  onChange={(e) => setSelectedKategoriId(e.target.value)}
                  className="w-full px-4 py-3 rounded-xl bg-slate-50/50 border border-slate-200/50 focus:outline-none focus:ring-2 focus:ring-teal-500/10 focus:border-teal-500 text-xs font-bold text-slate-700 transition-all cursor-pointer"
                >
                  <option value="">-- Pilih Jenis {subKategori} --</option>
                  {filteredKategori.map((kat) => {
                    const cleanName = kat.nama.replace(/^\[.*?\]\s*/, "")
                    return (
                      <option key={kat.id} value={kat.id}>
                        {cleanName} ({kat.poin > 0 ? `+${kat.poin}` : kat.poin} Poin)
                      </option>
                    )
                  })}
                </select>
              </div>

              {/* Poin Diberikan (Locked Display) */}
              <div>
                <label className="block text-[9px] font-black text-slate-455 uppercase tracking-widest mb-1.5">
                  Poin Diberikan
                </label>
                <div className="flex items-center gap-3">
                  <div className="w-24 px-4 py-3 rounded-xl bg-slate-100 border border-slate-200/80 text-xs font-black text-slate-700 text-center">
                    {activeKategori ? (activeKategori.poin > 0 ? `+${activeKategori.poin}` : activeKategori.poin) : 0}
                  </div>
                  <span className="text-[10px] text-slate-450 font-bold">
                    * Nilai poin terkunci otomatis sesuai ketentuan Master Jenis Kategori.
                  </span>
                </div>
              </div>
            </div>

            {/* Right Column Fields */}
            <div className="space-y-4">
              {/* Pilih Siswa Multi Select */}
              <div className="relative">
                <label className="block text-[9px] font-black text-slate-455 uppercase tracking-widest mb-1.5">
                  Pilih Siswa (Bisa Lebih Dari Satu) <span className="text-rose-500">*</span>
                </label>
                <div className="relative">
                  <Search className="absolute left-3 top-2.5 text-muted-foreground w-4 h-4" />
                  <Input
                    placeholder="Ketik nama, NISN, atau kelas siswa..."
                    value={siswaSearchInput}
                    onChange={(e) => {
                      setSiswaSearchInput(e.target.value)
                      setShowSiswaDropdown(true)
                    }}
                    onFocus={() => setShowSiswaDropdown(true)}
                    className="pl-9 h-10"
                  />
                  {showSiswaDropdown && (
                    <div ref={dropdownRef} className="absolute left-0 right-0 top-full mt-1 bg-background border border-slate-100 rounded-2xl shadow-xl z-50 max-h-56 overflow-y-auto">
                      <table className="w-full border-collapse">
                        <thead>
                          <tr className="border-b border-slate-100 text-left text-[9px] font-black text-slate-400 uppercase tracking-widest">
                            <th className="py-3 px-3 w-10 text-center">Pilih</th>
                            <th className="py-3 px-3">Nama Siswa</th>
                            <th className="py-3 px-3">NISN</th>
                            <th className="py-3 px-3">Kelas</th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-50">
                          {filteredSiswaSearch.length === 0 ? (
                            <tr>
                              <td colSpan={4} className="py-8 text-center text-xs text-slate-400 font-bold">
                                Tidak ada siswa ditemukan
                              </td>
                            </tr>
                          ) : (
                            filteredSiswaSearch.map((s) => {
                              const isSelected = selectedSiswaIds.includes(s.id)
                              return (
                                <tr
                                  key={s.id}
                                  onClick={() => handleToggleSiswa(s.id)}
                                  className={`cursor-pointer transition-all ${
                                    isSelected ? "bg-teal-50/40" : "hover:bg-slate-50/60"
                                  }`}
                                >
                                  <td className="py-2.5 px-3 text-center">
                                    {isSelected ? (
                                      <Check size={14} className="text-teal-600 stroke-[3] mx-auto" />
                                    ) : (
                                      <span className="w-4 h-4 rounded-full border border-slate-200 block mx-auto" />
                                    )}
                                  </td>
                                  <td className="py-2.5 px-3 font-bold text-slate-700 text-xs">{s.namaLengkap}</td>
                                  <td className="py-2.5 px-3 text-slate-500 text-xs font-bold">{s.nisn || "-"}</td>
                                  <td className="py-2.5 px-3 text-slate-500 text-xs font-bold">{getKelasNama(s.id)}</td>
                                </tr>
                              )
                            })
                          )}
                        </tbody>
                      </table>
                    </div>
                  )}
                </div>

                {/* Selected Students badge list */}
                <div className="mt-2.5 flex flex-wrap gap-1.5">
                  {selectedSiswaIds.length === 0 ? (
                    <span className="text-[10px] text-slate-400 font-bold block py-1.5">Belum ada siswa terpilih.</span>
                  ) : (
                    selectedSiswaIds.map((sId) => {
                      const match = siswaList?.find(s => s.id === sId)
                      return (
                        <span
                          key={sId}
                          className="inline-flex items-center gap-1 bg-slate-100 border border-slate-200 text-slate-655 pl-2.5 pr-1.5 py-1 rounded-xl text-[10px] font-black uppercase tracking-wider"
                        >
                          <span>{match?.namaLengkap || "Siswa"}</span>
                          <button
                            type="button"
                            onClick={() => handleToggleSiswa(sId)}
                            className="w-4 h-4 rounded-full flex items-center justify-center hover:bg-slate-250 text-slate-500 hover:text-slate-800 transition-all"
                          >
                            <X size={10} />
                          </button>
                        </span>
                      )
                    })
                  )}
                </div>
              </div>

              {/* Grid: Tanggal & Petugas */}
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-[9px] font-black text-slate-455 uppercase tracking-widest mb-1.5">
                    Tanggal & Waktu (WIB)
                  </label>
                  <input
                    type="datetime-local"
                    value={tanggalKejadian}
                    onChange={(e) => setTanggalKejadian(e.target.value)}
                    className="w-full px-4 py-3 rounded-xl bg-slate-50/50 border border-slate-200/50 focus:outline-none focus:ring-2 focus:ring-teal-500/10 focus:border-teal-500 text-xs font-bold text-slate-700 cursor-pointer"
                  />
                </div>

                <div>
                  <label className="block text-[9px] font-black text-slate-455 uppercase tracking-widest mb-1.5">
                    Petugas Penginput (Otomatis)
                  </label>
                  <div className="w-full px-4 py-3 rounded-xl bg-slate-100 border border-slate-200/80 text-xs font-bold text-slate-500 flex items-center gap-2">
                    <User size={14} />
                    <span>{session?.user?.name || "Fatimah S.Pd"}</span>
                  </div>
                </div>
              </div>

              {/* Tindak Lanjut Ter-generate */}
              <div>
                <label className="block text-[9px] font-black text-slate-455 uppercase tracking-widest mb-1.5">
                  Tindak Lanjut / Sanksi / Penghargaan (Ter-generate otomatis)
                </label>
                <div className="w-full px-4 py-3 rounded-xl bg-slate-100 border border-slate-200/80 text-xs font-bold text-slate-500">
                  {autoGeneratedAction}
                </div>
              </div>
            </div>

            {/* Bottom Fields span width */}
            <div className="md:col-span-2 space-y-4">
              <div>
                <label className="block text-[9px] font-black text-slate-455 uppercase tracking-widest mb-1.5">
                  Keterangan / Kronologi <span className="text-rose-500">*</span>
                </label>
                <textarea
                  required
                  rows={3}
                  placeholder="Tambahkan catatan detail kejadian..."
                  value={kronologi}
                  onChange={(e) => setKronologi(e.target.value)}
                  className="w-full px-4 py-3 rounded-xl bg-slate-50/50 border border-slate-200/50 focus:outline-none focus:ring-2 focus:ring-teal-500/10 focus:border-teal-500 text-xs font-bold text-slate-700 placeholder-slate-400 transition-all duration-300"
                />
              </div>

              {/* Image Upload Area Mockup */}
              <div>
                <label className="block text-[9px] font-black text-slate-455 uppercase tracking-widest mb-1.5">
                  Foto Bukti Kejadian (Opsional)
                </label>
                <div className="border border-dashed border-slate-200/80 rounded-2xl p-6 bg-slate-50/10 hover:bg-slate-50/30 transition-all flex flex-col items-center justify-center cursor-pointer">
                  <Upload className="text-slate-400 w-8 h-8 mb-2" />
                  <span className="text-xs font-black text-slate-650 uppercase tracking-wider">Unggah Foto Bukti</span>
                  <span className="text-[9px] text-slate-400 mt-1 text-center max-w-sm font-bold">
                    Format JPG, JPEG atau PNG maks 2MB. Foto dikompresi otomatis & disinkronisasikan ke Supabase agar dapat dilihat di semua perangkat Anda.
                  </span>
                </div>
              </div>

              {/* Footer Buttons */}
              <div className="flex items-center justify-end gap-3 pt-4 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => {
                    setSelectedKategoriId("")
                    setSelectedSiswaIds([])
                    setKronologi("")
                  }}
                  className="px-6 py-3 rounded-xl border border-slate-200 hover:bg-slate-50 text-slate-500 text-xs font-black uppercase tracking-wider transition-all cursor-pointer"
                >
                  Batal
                </button>
                <button
                  type="submit"
                  disabled={createSikapMutation.isPending}
                  className="px-6 py-3 rounded-xl bg-gradient-to-r from-teal-600 to-emerald-600 hover:from-teal-700 hover:to-emerald-700 text-white text-xs font-black uppercase tracking-wider transition-all flex items-center justify-center gap-2 shadow-md shadow-teal-500/5 cursor-pointer disabled:opacity-50"
                >
                  {createSikapMutation.isPending ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                  ) : (
                    <span>Simpan Poin</span>
                  )}
                </button>
              </div>
            </div>
          </form>
        </div>
      ) : activeTab === "menunggu" ? (
        /* Tab 2: Menunggu Validasi BK */
        <div className="neumo-card bg-background rounded-3xl p-6 space-y-6">
          <div className="flex items-center justify-between pb-4 border-b border-slate-100">
            <div>
              <h3 className="text-sm font-black text-slate-800 uppercase tracking-wider">Menunggu Validasi BK</h3>
              <p className="text-[10px] text-slate-400 font-bold uppercase mt-1">Daftar input poin yang menunggu persetujuan.</p>
            </div>
            <div className="flex items-center gap-2">
              <span className="px-3 py-1.5 rounded-full bg-amber-50 border border-amber-200 text-amber-700 text-[9px] font-black uppercase tracking-wider">
                {pendingLogs.length} Antrean
              </span>
            </div>
          </div>

          <div className="hidden md:block overflow-x-auto">
            <table className="w-full border-collapse">
              <thead>
                <tr className="border-b border-slate-100 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">
                  <th className="py-4 px-4">Tanggal</th>
                  <th className="py-4 px-4">Siswa</th>
                  <th className="py-4 px-4">Jenis Sikap</th>
                  <th className="py-4 px-4 text-center">Poin</th>
                  <th className="py-4 px-4">Pelapor</th>
                  <th className="py-4 px-4 text-center">Aksi</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50 text-xs font-bold text-slate-700">
                {pendingLogs.length === 0 ? (
                  <tr>
                    <td colSpan={6} className="py-12 text-center text-slate-400 font-bold">
                      Tidak ada entri poin yang menunggu validasi BK.
                    </td>
                  </tr>
                ) : (
                  pendingLogs.map((item: any) => {
                    const cleanName = item.kategori?.nama ? item.kategori.nama.replace(/^\[.*?\]\s*/, "") : "—"
                    return (
                      <tr key={item.id} className="hover:bg-slate-50/40">
                        <td className="py-4 px-4 text-slate-500 whitespace-nowrap">
                          {format(new Date(item.createdAt), "dd MMM yyyy, HH:mm", { locale: id })}
                        </td>
                        <td className="py-4 px-4">
                          <div className="font-black text-slate-800 uppercase leading-none">{item.siswa?.namaLengkap || "—"}</div>
                          <span className="text-[9px] text-slate-400 font-extrabold uppercase mt-1 block">
                            Kelas: {item.siswa?.kelasId || "—"}
                          </span>
                        </td>
                        <td className="py-4 px-4">
                          <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[9px] font-black uppercase tracking-wider ${
                            item.poin > 0
                              ? "bg-emerald-100 text-emerald-700"
                              : "bg-rose-100 text-rose-700"
                          }`}>
                            {cleanName}
                          </span>
                        </td>
                        <td className={`py-4 px-4 text-center font-black ${
                          item.poin > 0 ? "text-emerald-600" : "text-rose-600"
                        }`}>
                          {item.poin > 0 ? `+${item.poin}` : item.poin}
                        </td>
                        <td className="py-4 px-4 text-slate-500 font-extrabold">
                          {item.guru?.namaLengkap || "Guru / Pengajar"}
                        </td>
                        <td className="py-4 px-4">
                          <div className="flex items-center justify-center gap-2">
                            <button
                              onClick={() => approveMutation.mutate({ id: item.id, status: "selesai" })}
                              disabled={approveMutation.isPending}
                              className="p-2 rounded-lg bg-emerald-50 border border-emerald-200 text-emerald-600 hover:bg-emerald-100 cursor-pointer disabled:opacity-50"
                              title="Setujui"
                            >
                              <Check size={14} />
                            </button>
                            <button
                              onClick={() => {
                                if (confirm("Apakah Anda yakin ingin menolak dan menghapus entri poin ini?")) {
                                  rejectMutation.mutate({ id: item.id })
                                }
                              }}
                              disabled={rejectMutation.isPending}
                              className="p-2 rounded-lg bg-rose-50 border border-rose-200 text-rose-600 hover:bg-rose-100 cursor-pointer disabled:opacity-50"
                              title="Tolak"
                            >
                              <X size={14} />
                            </button>
                          </div>
                        </td>
                      </tr>
                    )
                  })
                )}
              </tbody>
            </table>
          </div>
        </div>
      ) : (
        /* Tab 3: Rekap List */
        <div className="neumo-card bg-background rounded-3xl p-6 space-y-6">
          <div className="flex flex-col sm:flex-row items-center gap-4 justify-between">
            {/* Search Input */}
            <div className="flex items-center gap-2 w-full sm:max-w-md">
              <div className="relative flex-1">
                <Search className="absolute left-3 top-2.5 text-muted-foreground w-4 h-4" />
                <Input
                  placeholder="Cari berdasarkan nama siswa, kategori sikap, atau petugas..."
                  value={searchRekapQuery}
                  onChange={(e) => setSearchRekapQuery(e.target.value)}
                  className="pl-9 h-10"
                />
              </div>
              <Button type="button" variant="secondary" className="h-10 px-4">
                Cari
              </Button>
            </div>

            {/* Filter Dropdown */}
            <div className="flex items-center gap-2 w-full sm:w-auto">
              <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest whitespace-nowrap">Filter Jenis:</span>
              <select
                value={filterRekapJenis}
                onChange={(e) => setFilterRekapJenis(e.target.value)}
                className="w-full sm:w-44 px-4 py-2.5 rounded-xl bg-slate-50/50 border border-slate-200/50 focus:outline-none text-xs font-bold text-slate-700 cursor-pointer"
              >
                <option value="all">Semua Jenis</option>
                <option value="negatif">Pelanggaran (Negatif)</option>
                <option value="positif">Prestasi (Positif)</option>
              </select>
            </div>
          </div>

          {/* Desktop Table View */}
          <div className="hidden md:block overflow-x-auto">
            <table className="w-full border-collapse">
              <thead>
                <tr className="border-b border-slate-100 text-left text-[10px] font-black text-slate-400 uppercase tracking-widest">
                  <th className="py-4 px-4 w-12 text-center">No</th>
                  <th className="py-4 px-4">Tanggal Kejadian</th>
                  <th className="py-4 px-4">Siswa</th>
                  <th className="py-4 px-4">Jenis Sikap & Deskripsi</th>
                  <th className="py-4 px-4 text-center">Poin</th>
                  <th className="py-4 px-4">Petugas Penginput</th>
                  <th className="py-4 px-4 text-center">Status Kasus</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50 text-xs font-bold text-slate-700">
                {isLoadingRiwayat ? (
                  <tr>
                    <td colSpan={7} className="py-12 text-center text-slate-400 font-bold">
                      Memuat data log rekap...
                    </td>
                  </tr>
                ) : filteredRekapList.length === 0 ? (
                  <tr>
                    <td colSpan={7} className="py-12 text-center text-slate-400 font-bold">
                      Tidak ada catatan riwayat e-poin ditemukan.
                    </td>
                  </tr>
                ) : (
                  filteredRekapList.map((item: any, idx: number) => {
                    const cleanName = item.kategori?.nama ? item.kategori.nama.replace(/^\[.*?\]\s*/, "") : "—"
                    return (
                      <tr key={item.id} className="hover:bg-slate-50/40">
                        <td className="py-4 px-4 text-center font-extrabold text-slate-400">{idx + 1}</td>
                        <td className="py-4 px-4 text-slate-500">
                          {format(new Date(item.createdAt), "dd MMM yyyy, HH:mm", { locale: id })}
                        </td>
                        <td className="py-4 px-4">
                          <div className="font-black text-slate-800 uppercase leading-none">{item.siswa?.namaLengkap || "—"}</div>
                          <span className="text-[9px] text-slate-400 font-extrabold uppercase mt-1 block">
                            Kelas: {item.siswa?.kelasId || "—"}
                          </span>
                        </td>
                        <td className="py-4 px-4 max-w-sm">
                          <div className="font-extrabold text-slate-800">{cleanName}</div>
                          {item.deskripsi && (
                            <p className="text-[10px] text-slate-450 font-normal mt-1 leading-normal italic">
                              "{item.deskripsi}"
                            </p>
                          )}
                        </td>
                        <td className="py-4 px-4 text-center">
                          <span
                            className={`inline-flex px-2 py-0.5 rounded-md text-[10px] font-black uppercase tracking-wider ${
                              item.poin > 0
                                ? "bg-emerald-50 text-emerald-600 border border-emerald-100"
                                : "bg-rose-50 text-rose-600 border border-rose-100"
                            }`}
                          >
                            {item.poin > 0 ? `+${item.poin}` : item.poin}
                          </span>
                        </td>
                        <td className="py-4 px-4 text-slate-500 font-extrabold">
                          {item.guru?.namaLengkap || "Admin Sistem"}
                        </td>
                        <td className="py-4 px-4 text-center">
                          <span
                            className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[9px] font-black uppercase tracking-wider ${
                              item.status === "selesai"
                                ? "bg-emerald-50 text-emerald-600 border border-emerald-100"
                                : item.status === "sedang_diproses"
                                  ? "bg-amber-50 text-amber-600 border border-amber-100 animate-pulse"
                                  : "bg-slate-100 text-slate-600 border border-slate-200"
                            }`}
                          >
                            {item.status === "selesai" && "Selesai"}
                            {item.status === "sedang_diproses" && "Sedang Diproses"}
                            {item.status === "belum_diproses" && "Belum Diproses"}
                          </span>
                        </td>
                      </tr>
                    )
                  })
                )}
              </tbody>
            </table>
          </div>

          {/* Mobile Card View List */}
          <div className="md:hidden space-y-4">
            {isLoadingRiwayat ? (
              <p className="text-center py-6 text-xs text-slate-400 font-bold">Memuat log rekap...</p>
            ) : filteredRekapList.length === 0 ? (
              <p className="text-center py-6 text-xs text-slate-400 font-bold">Tidak ada catatan riwayat ditemukan.</p>
            ) : (
              filteredRekapList.map((item: any) => {
                const cleanName = item.kategori?.nama ? item.kategori.nama.replace(/^\[.*?\]\s*/, "") : "—"
                return (
                  <div key={item.id} className="p-4 rounded-2xl border border-slate-100 bg-slate-50/20 space-y-3">
                    <div className="flex justify-between items-start">
                      <div>
                        <h4 className="text-xs font-black text-slate-800 uppercase leading-none">{item.siswa?.namaLengkap}</h4>
                        <span className="text-[9px] text-slate-400 font-extrabold uppercase mt-1 block">Kelas: {item.siswa?.kelasId}</span>
                      </div>
                      <span
                        className={`inline-flex px-2 py-0.5 rounded-md text-[9px] font-black uppercase tracking-wider ${
                          item.poin > 0 ? "bg-emerald-50 text-emerald-600" : "bg-rose-50 text-rose-600"
                        }`}
                      >
                        {item.poin > 0 ? `+${item.poin}` : item.poin}
                      </span>
                    </div>

                    <div className="text-[11px] text-slate-655 space-y-1">
                      <p className="font-extrabold text-slate-700">{cleanName}</p>
                      {item.deskripsi && <p className="italic text-slate-450 font-normal">"{item.deskripsi}"</p>}
                    </div>

                    <div className="flex justify-between items-center border-t border-slate-100 pt-3 text-[10px]">
                      <span className="text-slate-400 font-extrabold">
                        {format(new Date(item.createdAt), "dd MMM, HH:mm", { locale: id })}
                      </span>
                      <span
                        className={`inline-flex px-2 py-0.5 rounded-full text-[9px] font-black uppercase tracking-wider ${
                          item.status === "selesai"
                            ? "bg-emerald-50 text-emerald-600"
                            : item.status === "sedang_diproses"
                              ? "bg-amber-50 text-amber-600"
                              : "bg-slate-100 text-slate-600"
                        }`}
                      >
                        {item.status === "selesai" && "Selesai"}
                        {item.status === "sedang_diproses" && "Proses"}
                        {item.status === "belum_diproses" && "Antrean"}
                      </span>
                    </div>
                  </div>
                )
              })
            )}
          </div>
        </div>
      )}
    </div>
  )
}
