import { pgTable, text, timestamp, boolean, integer } from "drizzle-orm/pg-core"
import { relations } from "drizzle-orm"
import { sekolah } from "./sekolah"
import { kelas } from "./kelas"

export const siswa = pgTable("siswa", {
  id: text("id").primaryKey(),
  sekolahId: text("sekolah_id").notNull().references(() => sekolah.id, { onDelete: "cascade" }),
  kelasId: text("kelas_id").references(() => kelas.id, { onDelete: "set null" }),
  nisn: text("nisn").notNull(),
  nisLokal: text("nis_lokal"),
  namaLengkap: text("nama_lengkap").notNull(),
  jenisKelamin: text("jenis_kelamin", { enum: ["L", "P"] }),
  tempatLahir: text("tempat_lahir"),
  tanggalLahir: timestamp("tanggal_lahir"),
  nik: text("nik"),
  agama: text("agama"),
  alamat: text("alamat"),
  noHpOrtu: text("no_hp_ortu"),
  emailSiswa: text("email_siswa"),
  foto: text("foto"),
  status: text("status", { enum: ["aktif", "lulus", "pindah", "keluar"] }).notNull().default("aktif"),
  hobi: text("hobi"),
  citacita: text("citacita"),
  jumlahSaudara: integer("jumlah_saudara"),
  anakKe: integer("anak_ke"),
  kewarganegaraan: text("kewarganegaraan").default("WNI"),
  pembiayaanSekolah: text("pembiayaan_sekolah"),
  noKartuKeluarga: text("no_kartu_keluarga"),
  namaKepalaKeluarga: text("nama_kepala_keluarga"),
  namaAyah: text("nama_ayah"),
  nikAyah: text("nik_ayah"),
  tempatLahirAyah: text("tempat_lahir_ayah"),
  tanggalLahirAyah: timestamp("tanggal_lahir_ayah"),
  pendidikanAyah: text("pendidikan_ayah"),
  pekerjaanAyah: text("pekerjaan_ayah"),
  penghasilanAyah: text("penghasilan_ayah"),
  statusAyah: text("status_ayah"),
  noHpAyah: text("no_hp_ayah"),
  kewarganegaraanAyah: text("kewarganegaraan_ayah").default("WNI"),
  provinsiAyah: text("provinsi_ayah"),
  kabupatenKotaAyah: text("kabupaten_kota_ayah"),
  kecamatanAyah: text("kecamatan_ayah"),
  kelurahanDesaAyah: text("kelurahan_desa_ayah"),
  rtAyah: text("rt_ayah"),
  rwAyah: text("rw_ayah"),
  alamatLengkapAyah: text("alamat_lengkap_ayah"),
  kodePosAyah: text("kode_pos_ayah"),
  statusKepemilikanRumahAyah: text("status_kepemilikan_rumah_ayah"),
  namaIbu: text("nama_ibu"),
  nikIbu: text("nik_ibu"),
  tempatLahirIbu: text("tempat_lahir_ibu"),
  tanggalLahirIbu: timestamp("tanggal_lahir_ibu"),
  pendidikanIbu: text("pendidikan_ibu"),
  pekerjaanIbu: text("pekerjaan_ibu"),
  penghasilanIbu: text("penghasilan_ibu"),
  statusIbu: text("status_ibu"),
  noHpIbu: text("no_hp_ibu"),
  kewarganegaraanIbu: text("kewarganegaraan_ibu").default("WNI"),
  alamatIbuSamaDenganAyah: boolean("alamat_ibu_sama_dengan_ayah").default(true),
  provinsiIbu: text("provinsi_ibu"),
  kabupatenKotaIbu: text("kabupaten_kota_ibu"),
  kecamatanIbu: text("kecamatan_ibu"),
  kelurahanDesaIbu: text("kelurahan_desa_ibu"),
  rtIbu: text("rt_ibu"),
  rwIbu: text("rw_ibu"),
  alamatLengkapIbu: text("alamat_lengkap_ibu"),
  kodePosIbu: text("kode_pos_ibu"),
  statusKepemilikanRumahIbu: text("status_kepemilikan_rumah_ibu"),
  namaWali: text("nama_wali"),
  nikWali: text("nik_wali"),
  tempatLahirWali: text("tempat_lahir_wali"),
  tanggalLahirWali: timestamp("tanggal_lahir_wali"),
  pendidikanWali: text("pendidikan_wali"),
  pekerjaanWali: text("pekerjaan_wali"),
  penghasilanWali: text("penghasilan_wali"),
  statusWali: text("status_wali"),
  noHpWali: text("no_hp_wali"),
  kewarganegaraanWali: text("kewarganegaraan_wali").default("WNI"),
  statusKepemilikanRumahWali: text("status_kepemilikan_rumah_wali"),
  provinsiWali: text("provinsi_wali"),
  kabupatenKotaWali: text("kabupaten_kota_wali"),
  kecamatanWali: text("kecamatan_wali"),
  kelurahanDesaWali: text("kelurahan_desa_wali"),
  rtWali: text("rt_wali"),
  rwWali: text("rw_wali"),
  alamatLengkapWali: text("alamat_lengkap_wali"),
  kodePosWali: text("kode_pos_wali"),
  statusTempatTinggalSiswa: text("status_tempat_tinggal_siswa"),
  jarakTempatTinggalKeSekolah: text("jarak_tempat_tinggal_ke_sekolah"),
  transportasiKeSekolah: text("transportasi_ke_sekolah"),
  waktuTempuhKeSekolah: text("waktu_tempuh_ke_sekolah"),
  usernameSiswa: text("username_siswa"),
  passwordSiswa: text("password_siswa"),
  sekolahAsal: text("sekolah_asal"),
  diterimaPadaTanggal: timestamp("diterima_pada_tanggal"),
  noHpWhatsapp: text("no_hp_whatsapp"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
})

export const siswaRelations = relations(siswa, ({ one }) => ({
  sekolah: one(sekolah, {
    fields: [siswa.sekolahId],
    references: [sekolah.id],
  }),
  kelas: one(kelas, {
    fields: [siswa.kelasId],
    references: [kelas.id],
  }),
}))
