import { Student, Teacher, Institution, NotificationItem } from './types';

export const PROVINCES = [
  "Aceh", "Sumatera Utara", "Sumatera Barat", "Riau", "Jambi", "Sumatera Selatan", "Bengkulu", "Lampung", 
  "Kepulauan Bangka Belitung", "Kepulauan Riau", "DKI Jakarta", "Jawa Barat", "Jawa Tengah", "DI Yogyakarta", 
  "Jawa Timur", "Banten", "Bali", "Nusa Tenggara Barat", "Nusa Tenggara Timur", "Kalimantan Barat", 
  "Kalimantan Tengah", "Kalimantan Selatan", "Kalimantan Timur", "Kalimantan Utara", "Sulawesi Utara", 
  "Sulawesi Tengah", "Sulawesi Selatan", "Sulawesi Tenggara", "Gorontalo", "Sulawesi Barat", "Maluku", 
  "Maluku Utara", "Papua", "Papua Barat", "Papua Selatan", "Papua Tengah", "Papua Pegunungan", "Papua Barat Daya"
];

export const MOCK_CITIES: Record<string, string[]> = {
  "Aceh": ["Kota Banda Aceh", "Kabupaten Aceh Besar", "Kabupaten Aceh Barat", "Kota Lhokseumawe", "Kota Sabang"],
  "Sumatera Utara": ["Kota Medan", "Kabupaten Deli Serdang", "Kota Binjai", "Kabupaten Langkat", "Kota Tebing Tinggi"],
  "Sumatera Barat": ["Kota Padang", "Kota Bukittinggi", "Kabupaten Padang Pariaman", "Kota Payakumbuh", "Kota Solok"],
  "Riau": ["Kota Pekanbaru", "Kabupaten Kampar", "Kota Dumai", "Kabupaten Bengkalis", "Kabupaten Siak"],
  "Jambi": ["Kota Jambi", "Kabupaten Muaro Jambi", "Kabupaten Bungo", "Kota Sungai Penuh"],
  "Sumatera Selatan": ["Kota Palembang", "Kota Prabumulih", "Kabupaten Ogan Ilir", "Kota Lubuklinggau", "Kabupaten Banyuasin"],
  "Bengkulu": ["Kota Bengkulu", "Kabupaten Rejang Lebong", "Kabupaten Bengkulu Utara"],
  "Lampung": ["Kota Bandar Lampung", "Kota Metro", "Kabupaten Lampung Selatan", "Kabupaten Lampung Tengah", "Kabupaten Tanggamus"],
  "Kepulauan Bangka Belitung": ["Kota Pangkalpinang", "Kabupaten Bangka", "Kabupaten Belitung"],
  "Kepulauan Riau": ["Kota Batam", "Kota Tanjungpinang", "Kabupaten Karimun", "Kabupaten Bintan"],
  "DKI Jakarta": ["Jakarta Selatan", "Jakarta Pusat", "Jakarta Barat", "Jakarta Timur", "Jakarta Utara", "Kepulauan Seribu"],
  "Jawa Barat": ["Kota Bandung", "Kabupaten Bandung", "Kabupaten Bandung Barat", "Kota Cimahi", "Kabupaten Bogor", "Kota Bekasi", "Kota Depok", "Kota Tasikmalaya", "Kabupaten Garut", "Kabupaten Sumedang", "Kota Sukabumi", "Kota Cirebon", "Kabupaten Karawang", "Kabupaten Purwakarta", "Kabupaten Subang"],
  "Jawa Tengah": ["Kota Semarang", "Kota Surakarta", "Kabupaten Banyumas", "Kabupaten Kudus", "Kota Magelang", "Kota Pekalongan", "Kota Salatiga", "Kota Tegal", "Kabupaten Cilacap", "Kabupaten Klaten"],
  "DI Yogyakarta": ["Kota Yogyakarta", "Kabupaten Sleman", "Kabupaten Bantul", "Kabupaten Gunungkidul", "Kabupaten Kulon Progo"],
  "Jawa Timur": ["Kota Surabaya", "Kota Malang", "Kabupaten Sidoarjo", "Kabupaten Gresik", "Kota Kediri", "Kota Madiun", "Kota Mojokerto", "Kota Pasuruan", "Kota Probolinggo", "Kota Batu", "Kabupaten Jember", "Kabupaten Banyuwangi"],
  "Banten": ["Kota Tangerang", "Kota Tangerang Selatan", "Kota Serang", "Kota Cilegon", "Kabupaten Tangerang", "Kabupaten Serang", "Kabupaten Lebak", "Kabupaten Pandeglang"],
  "Bali": ["Kota Denpasar", "Kabupaten Badung", "Kabupaten Gianyar", "Kabupaten Buleleng", "Kabupaten Tabanan", "Kabupaten Karangasem"],
  "Nusa Tenggara Barat": ["Kota Mataram", "Kabupaten Lombok Barat", "Kabupaten Lombok Timur", "Kota Bima", "Kabupaten Sumbawa"],
  "Nusa Tenggara Timur": ["Kota Kupang", "Kabupaten Sikka", "Kabupaten Manggarai", "Kabupaten Ende", "Kabupaten Belu"],
  "Kalimantan Barat": ["Kota Pontianak", "Kabupaten Kubu Raya", "Kota Singkawang", "Kabupaten Ketapang", "Kabupaten Sintang"],
  "Kalimantan Tengah": ["Kota Palangka Raya", "Kabupaten Kotawaringin Timur", "Kabupaten Kotawaringin Barat", "Kabupaten Kapuas"],
  "Kalimantan Selatan": ["Kota Banjarmasin", "Kota Banjarbaru", "Kabupaten Banjar", "Kabupaten Tanah Laut", "Kabupaten Tabalong"],
  "Kalimantan Timur": ["Kota Samarinda", "Kota Balikpapan", "Kabupaten Kutai Kartanegara", "Kota Bontang", "Kabupaten Paser"],
  "Kalimantan Utara": ["Kota Tarakan", "Kabupaten Bulungan", "Kabupaten Malinau", "Kabupaten Nunukan"],
  "Sulawesi Utara": ["Kota Manado", "Kota Bitung", "Kabupaten Minahasa", "Kota Tomohon", "Kota Kotamobagu"],
  "Sulawesi Tengah": ["Kota Palu", "Kabupaten Sigi", "Kabupaten Donggala", "Kabupaten Banggai", "Kabupaten Poso"],
  "Sulawesi Selatan": ["Kota Makassar", "Kota Parepare", "Kabupaten Gowa", "Kabupaten Bone", "Kota Palopo", "Kabupaten Maros", "Kabupaten Bulukumba"],
  "Sulawesi Tenggara": ["Kota Kendari", "Kota Bau-Bau", "Kabupaten Kolaka", "Kabupaten Konawe", "Kabupaten Muna"],
  "Gorontalo": ["Kota Gorontalo", "Kabupaten Gorontalo", "Kabupaten Boalemo", "Kabupaten Bone Bolango"],
  "Sulawesi Barat": ["Kabupaten Mamuju", "Kabupaten Polewali Mandar", "Kabupaten Majene", "Kabupaten Mamasa"],
  "Maluku": ["Kota Ambon", "Kabupaten Maluku Tengah", "Kabupaten Maluku Tenggara", "Kabupaten Buru"],
  "Maluku Utara": ["Kota Ternate", "Kota Tidore Kepulauan", "Kabupaten Halmahera Utara", "Kabupaten Halmahera Selatan"],
  "Papua": ["Kota Jayapura", "Kabupaten Jayapura", "Kabupaten Biak Numfor", "Kabupaten Kepulauan Yapen"],
  "Papua Barat": ["Kabupaten Manokwari", "Kabupaten Fakfak", "Kabupaten Teluk Bintuni"],
  "Papua Selatan": ["Kabupaten Merauke", "Kabupaten Boven Digoel", "Kabupaten Mappi"],
  "Papua Tengah": ["Kabupaten Nabire", "Kabupaten Mimika", "Kabupaten Paniai"],
  "Papua Pegunungan": ["Kabupaten Jayawijaya", "Kabupaten Lanny Jaya", "Kabupaten Tolikara"],
  "Papua Barat Daya": ["Kota Sorong", "Kabupaten Sorong", "Kabupaten Raja Ampat"]
};

export const MOCK_DISTRICTS: Record<string, string[]> = {
  "Kota Bandung": ["Kecamatan Coblong", "Kecamatan Lengkong", "Kecamatan Regol", "Kecamatan Kutawaringin"],
  "Kabupaten Bandung": ["Kecamatan Kutawaringin", "Kecamatan Soreang", "Kecamatan Margahayu"],
  "Jakarta Selatan": ["Kecamatan Kebayoran Baru", "Kecamatan Cilandak", "Kecamatan Tebet"],
  "Jakarta Pusat": ["Kecamatan Menteng", "Kecamatan Tanah Abang", "Kecamatan Gambir"]
};

export const MOCK_SUBDISTRICTS: Record<string, string[]> = {
  "Kecamatan Coblong": ["Kelurahan Dago", "Kelurahan Sadang Serang", "Kelurahan Sekeloa"],
  "Kecamatan Kutawaringin": ["Kelurahan Cibodas", "Kelurahan Jelegong", "Kelurahan Buninagara"],
  "Kecamatan Kebayoran Baru": ["Kelurahan Selong", "Kelurahan Kramat Pela", "Kelurahan Gandaria Utara"],
  "Kecamatan Soreang": ["Kelurahan Soreang", "Kelurahan Sekarwangi", "Kelurahan Pamekaran"]
};

export const INITIAL_INSTITUTION: Institution = {
  name: "MTS AT-TURMUDZI",
  npsn: "20278120",
  accreditation: "A",
  curriculum: "Kurikulum Merdeka",
  principal: "Drs. H. Ahmad Fauzi",
  email: "info@atsurmudzi.sch.id",
  website: "https://www.atsurmudzi.sch.id",
  phone: "(022) 5892 1234",
  address: "Jl. Desa Cibodas No. 85, Kel. Cibodas, Kec. Kutawaringin, Kab. Bandung, Jawa Barat",
  organizer: "Yayasan Wakaf At-Turmudzi",
  level: "MTS (Madrasah Tsanawiyah)",
  status: "Swasta / Aktif",
  academicYear: "2025/2026",
  semester: "GANJIL",
  social: {
    instagram: { user: "@mtsaturmudzi", url: "https://instagram.com/mtsaturmudzi" },
    facebook: { user: "mts.aturmudzi", url: "https://facebook.com/mts.aturmudzi" },
    tiktok: { user: "mts.aturmudzi", url: "https://tiktok.com/@mts.aturmudzi" },
    youtube: { user: "MTs At-Turmudzi TV", url: "https://youtube.com/@mtsaturmudzi" }
  },
  logo: ""
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    title: "Pengumuman Rapat Wali Murid",
    message: "Undangan rapat wali murid kelas 7-A s.d 7-C akan diselenggarakan pada Sabtu ini pukul 09.00 WIB.",
    time: "2 jam yang lalu",
    read: false
  },
  {
    id: "notif-2",
    title: "Sinkronisasi Dapodik Berhasil",
    message: "Data lembaga untuk periode semester ganjil 2025/2026 telah berhasil disinkronkan ke server pusat.",
    time: "1 hari yang lalu",
    read: true
  },
  {
    id: "notif-3",
    title: "Pembaruan Versi Sistem v1.0.5",
    message: "Sistem Manajemen Lembaga (Core Management) telah diperbarui ke versi v1.0.5 dengan fitur multi-tab data siswa.",
    time: "3 hari yang lalu",
    read: true
  }
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: "std-1",
    nisn: "0123456789",
    nis: "889210",
    nama: "Andi Setiawan",
    username: "andi_setiawan",
    kelas: "Kelas 7-A",
    jk: "Laki-laki",
    tempatLahir: "Bandung",
    tanggalLahir: "2012-05-12",
    wali: "Budi Santoso",
    status: "Aktif",
    nik: "3204111205120001",
    kewarganegaraan: "WNI",
    password: "password123",
    jumlahSaudara: "2",
    anakKe: "1",
    agama: "Islam",
    citaCita: "TNI/Polri",
    hp: "081234567890",
    email: "andi.setiawan@gmail.com",
    hoby: "Olahraga",
    pembiaya: "Orang Tua",
    foto: "",
    ayah: {
      nama: "Budi Santoso",
      status: "Masih Hidup",
      wn: "WNI",
      nik: "3204111508750002",
      tempatLahir: "Bandung",
      tanggalLahir: "1975-08-15",
      pendidikan: "SMA/Sederajat",
      pekerjaan: "Wiraswasta",
      penghasilan: "3.500.001 - 4.800.000",
      hp: "08122334455"
    },
    ibu: {
      nama: "Siti Aminah",
      status: "Masih Hidup",
      wn: "WNI",
      nik: "3204112010800003",
      tempatLahir: "Bandung",
      tanggalLahir: "1980-10-20",
      pendidikan: "SMP/Sederajat",
      pekerjaan: "Tidak Bekerja",
      penghasilan: "Dibawah 800.000",
      hp: "08122334466"
    },
    waliData: {
      statusWali: "Sama dengan ayah kandung",
      nama: "Budi Santoso",
      wn: "WNI",
      nik: "3204111508750002",
      hp: "08122334455",
      pendidikan: "SMA/Sederajat",
      pekerjaan: "Wiraswasta",
      penghasilan: "3.500.001 - 4.800.000",
      hubungan: "Ayah Kandung"
    },
    alamat: {
      ayah: {
        kepemilikan: "Milik Sendiri",
        prov: "Jawa Barat",
        kab: "Kabupaten Bandung",
        kec: "Kecamatan Kutawaringin",
        kel: "Kelurahan Cibodas",
        rt: "03",
        rw: "05",
        kodepos: "40911",
        jalan: "Jl. Desa Cibodas No. 42"
      },
      ibu: {
        samaDenganAyah: true,
        kepemilikan: "Milik Sendiri",
        prov: "Jawa Barat",
        kab: "Kabupaten Bandung",
        kec: "Kecamatan Kutawaringin",
        kel: "Kelurahan Cibodas",
        rt: "03",
        rw: "05",
        kodepos: "40911",
        jalan: "Jl. Desa Cibodas No. 42"
      },
      wali: {
        statusAlamatWali: "Sama dengan ayah kandung",
        kepemilikan: "Milik Sendiri",
        prov: "Jawa Barat",
        kab: "Kabupaten Bandung",
        kec: "Kecamatan Kutawaringin",
        kel: "Kelurahan Cibodas",
        rt: "03",
        rw: "05",
        kodepos: "40911",
        jalan: "Jl. Desa Cibodas No. 42"
      },
      domisili: {
        statusTempatTinggal: "Tinggal dengan Ayah Kandung",
        jarak: "Kurang dari 5 KM",
        transportasi: "Jalan Kaki",
        waktuTempuh: "1 - 10 Menit"
      }
    }
  },
  {
    id: "std-2",
    nisn: "0134567890",
    nis: "889211",
    nama: "Siti Rahmawati",
    username: "siti_rahma",
    kelas: "Kelas 8-B",
    jk: "Perempuan",
    tempatLahir: "Sumedang",
    tanggalLahir: "2011-09-24",
    wali: "Ahmad Dahlan",
    status: "Aktif",
    nik: "3211052409110002",
    kewarganegaraan: "WNI",
    password: "password123",
    jumlahSaudara: "1",
    anakKe: "2",
    agama: "Islam",
    citaCita: "Dokter",
    hp: "087766554433",
    email: "siti.rahma@gmail.com",
    hoby: "Membaca",
    pembiaya: "Orang Tua",
    foto: "",
    ayah: {
      nama: "Ahmad Dahlan",
      status: "Masih Hidup",
      wn: "WNI",
      nik: "3211051512700004",
      tempatLahir: "Sumedang",
      tanggalLahir: "1970-12-15",
      pendidikan: "D4/S1",
      pekerjaan: "Guru/Dosen",
      penghasilan: "4.800.001 - 6.500.000",
      hp: "08771122334"
    },
    ibu: {
      nama: "Yuyun Wahyuni",
      status: "Masih Hidup",
      wn: "WNI",
      nik: "3211050505750005",
      tempatLahir: "Sumedang",
      tanggalLahir: "1975-05-05",
      pendidikan: "SMA/Sederajat",
      pekerjaan: "Pedagang",
      penghasilan: "1.200.001 - 1.800.000",
      hp: "08771122335"
    },
    waliData: {
      statusWali: "Sama dengan ayah kandung",
      nama: "Ahmad Dahlan",
      wn: "WNI",
      nik: "3211051512700004",
      hp: "08771122334",
      pendidikan: "D4/S1",
      pekerjaan: "Guru/Dosen",
      penghasilan: "4.800.001 - 6.500.000",
      hubungan: "Ayah Kandung"
    },
    alamat: {
      ayah: {
        kepemilikan: "Milik Sendiri",
        prov: "Jawa Barat",
        kab: "Kota Bandung",
        kec: "Kecamatan Coblong",
        kel: "Kelurahan Dago",
        rt: "02",
        rw: "11",
        kodepos: "40135",
        jalan: "Jl. Dago Elok No. 15"
      },
      ibu: {
        samaDenganAyah: true,
        kepemilikan: "Milik Sendiri",
        prov: "Jawa Barat",
        kab: "Kota Bandung",
        kec: "Kecamatan Coblong",
        kel: "Kelurahan Dago",
        rt: "02",
        rw: "11",
        kodepos: "40135",
        jalan: "Jl. Dago Elok No. 15"
      },
      wali: {
        statusAlamatWali: "Sama dengan ayah kandung",
        kepemilikan: "Milik Sendiri",
        prov: "Jawa Barat",
        kab: "Kota Bandung",
        kec: "Kecamatan Coblong",
        kel: "Kelurahan Dago",
        rt: "02",
        rw: "11",
        kodepos: "40135",
        jalan: "Jl. Dago Elok No. 15"
      },
      domisili: {
        statusTempatTinggal: "Tinggal dengan Ayah Kandung",
        jarak: "Antara 5 - 10 KM",
        transportasi: "Sepeda Motor",
        waktuTempuh: "10 - 19 Menit"
      }
    }
  },
  {
    id: "std-3",
    nisn: "0145678901",
    nis: "889212",
    nama: "Muhammad Rayhan",
    username: "m_rayhan",
    kelas: "Kelas 9-A",
    jk: "Laki-laki",
    tempatLahir: "Bandung",
    tanggalLahir: "2010-02-18",
    wali: "Deddy Sudrajat",
    status: "Aktif",
    nik: "3204111802100005",
    kewarganegaraan: "WNI",
    password: "password123",
    jumlahSaudara: "0",
    anakKe: "1",
    agama: "Islam",
    citaCita: "Wiraswasta",
    hp: "081299887766",
    email: "rayhan@gmail.com",
    hoby: "Kesenian",
    pembiaya: "Orang Tua",
    foto: "",
    ayah: {
      nama: "Deddy Sudrajat",
      status: "Masih Hidup",
      wn: "WNI",
      nik: "3204111212680009",
      tempatLahir: "Ciamis",
      tanggalLahir: "1968-12-12",
      pendidikan: "D4/S1",
      pekerjaan: "Pegawai Swasta",
      penghasilan: "6.500.001 - 10.000.000",
      hp: "081290001"
    },
    ibu: {
      nama: "Rina Marlina",
      status: "Masih Hidup",
      wn: "WNI",
      nik: "3204110504720008",
      tempatLahir: "Garut",
      tanggalLahir: "1972-04-05",
      pendidikan: "SMA/Sederajat",
      pekerjaan: "Wiraswasta",
      penghasilan: "1.800.001 - 2.500.000",
      hp: "081290002"
    },
    waliData: {
      statusWali: "Sama dengan ayah kandung",
      nama: "Deddy Sudrajat",
      wn: "WNI",
      nik: "3204111212680009",
      hp: "081290001",
      pendidikan: "D4/S1",
      pekerjaan: "Pegawai Swasta",
      penghasilan: "6.500.001 - 10.000.000",
      hubungan: "Ayah Kandung"
    },
    alamat: {
      ayah: {
        kepemilikan: "Milik Sendiri",
        prov: "Jawa Barat",
        kab: "Kabupaten Bandung",
        kec: "Kecamatan Kutawaringin",
        kel: "Kelurahan Jelegong",
        rt: "01",
        rw: "03",
        kodepos: "40912",
        jalan: "Komp. Gading Tutuka Blok C/10"
      },
      ibu: {
        samaDenganAyah: true,
        kepemilikan: "Milik Sendiri",
        prov: "Jawa Barat",
        kab: "Kabupaten Bandung",
        kec: "Kecamatan Kutawaringin",
        kel: "Kelurahan Jelegong",
        rt: "01",
        rw: "03",
        kodepos: "40912",
        jalan: "Komp. Gading Tutuka Blok C/10"
      },
      wali: {
        statusAlamatWali: "Sama dengan ayah kandung",
        kepemilikan: "Milik Sendiri",
        prov: "Jawa Barat",
        kab: "Kabupaten Bandung",
        kec: "Kecamatan Kutawaringin",
        kel: "Kelurahan Jelegong",
        rt: "01",
        rw: "03",
        kodepos: "40912",
        jalan: "Komp. Gading Tutuka Blok C/10"
      },
      domisili: {
        statusTempatTinggal: "Tinggal dengan Ayah Kandung",
        jarak: "Kurang dari 5 KM",
        transportasi: "Sepeda Motor",
        waktuTempuh: "10 - 19 Menit"
      }
    }
  },
  {
    id: "std-4",
    nisn: "0156789012",
    nis: "889213",
    nama: "Dewi Lestari",
    username: "dewi_lestari",
    kelas: "Kelas 7-B",
    jk: "Perempuan",
    tempatLahir: "Bandung",
    tanggalLahir: "2012-08-05",
    wali: "Wawan Hermawan",
    status: "Aktif",
    nik: "3204124508120002",
    kewarganegaraan: "WNI",
    password: "password123",
    jumlahSaudara: "3",
    anakKe: "3",
    agama: "Islam",
    citaCita: "Dosen/Guru",
    hp: "085233445566",
    email: "dewi.lestari@gmail.com",
    hoby: "Menulis",
    pembiaya: "Orang Tua",
    foto: "",
    ayah: {
      nama: "Wawan Hermawan",
      status: "Masih Hidup",
      wn: "WNI",
      nik: "3204121403730005",
      tempatLahir: "Bandung",
      tanggalLahir: "1973-03-14",
      pendidikan: "SMA/Sederajat",
      pekerjaan: "Wiraswasta",
      penghasilan: "1.800.001 - 2.500.000",
      hp: "0852111222"
    },
    ibu: {
      nama: "Sukaesih",
      status: "Masih Hidup",
      wn: "WNI",
      nik: "3204125011760004",
      tempatLahir: "Bandung",
      tanggalLahir: "1976-11-10",
      pendidikan: "SMP/Sederajat",
      pekerjaan: "Pedagang",
      penghasilan: "800.001 - 1.200.000",
      hp: "0852111333"
    },
    waliData: {
      statusWali: "Sama dengan ayah kandung",
      nama: "Wawan Hermawan",
      wn: "WNI",
      nik: "3204121403730005",
      hp: "0852111222",
      pendidikan: "SMA/Sederajat",
      pekerjaan: "Wiraswasta",
      penghasilan: "1.800.001 - 2.500.000",
      hubungan: "Ayah Kandung"
    },
    alamat: {
      ayah: {
        kepemilikan: "Milik Sendiri",
        prov: "Jawa Barat",
        kab: "Kabupaten Bandung",
        kec: "Kecamatan Kutawaringin",
        kel: "Kelurahan Cibodas",
        rt: "01",
        rw: "04",
        kodepos: "40911",
        jalan: "Jl. Raya Cibodas No. 12"
      },
      ibu: {
        samaDenganAyah: true,
        kepemilikan: "Milik Sendiri",
        prov: "Jawa Barat",
        kab: "Kabupaten Bandung",
        kec: "Kecamatan Kutawaringin",
        kel: "Kelurahan Cibodas",
        rt: "01",
        rw: "04",
        kodepos: "40911",
        jalan: "Jl. Raya Cibodas No. 12"
      },
      wali: {
        statusAlamatWali: "Sama dengan ayah kandung",
        kepemilikan: "Milik Sendiri",
        prov: "Jawa Barat",
        kab: "Kabupaten Bandung",
        kec: "Kecamatan Kutawaringin",
        kel: "Kelurahan Cibodas",
        rt: "01",
        rw: "04",
        kodepos: "40911",
        jalan: "Jl. Raya Cibodas No. 12"
      },
      domisili: {
        statusTempatTinggal: "Tinggal dengan Ayah Kandung",
        jarak: "Kurang dari 5 KM",
        transportasi: "Jalan Kaki",
        waktuTempuh: "1 - 10 Menit"
      }
    }
  },
  {
    id: "std-5",
    nisn: "0167890123",
    nis: "889214",
    nama: "Fajar Ramadhan",
    username: "fajar_ramadhan",
    kelas: "Kelas 9-B",
    jk: "Laki-laki",
    tempatLahir: "Garut",
    tanggalLahir: "2010-09-10",
    wali: "Tatang Sutisna",
    status: "Non-Aktif",
    nik: "3205111009100001",
    kewarganegaraan: "WNI",
    password: "password123",
    jumlahSaudara: "4",
    anakKe: "1",
    agama: "Islam",
    citaCita: "Ilmuan",
    hp: "081344556677",
    email: "fajar.ramadhan@gmail.com",
    hoby: "Membaca",
    pembiaya: "Orang Tua",
    foto: "",
    ayah: {
      nama: "Tatang Sutisna",
      status: "Masih Hidup",
      wn: "WNI",
      nik: "3205111512690001",
      tempatLahir: "Garut",
      tanggalLahir: "1969-12-15",
      pendidikan: "SD/Sederajat",
      pekerjaan: "Petani/Peternak",
      penghasilan: "800.001 - 1.200.000",
      hp: "0813111222"
    },
    ibu: {
      nama: "Nengsih",
      status: "Masih Hidup",
      wn: "WNI",
      nik: "3205114510730002",
      tempatLahir: "Garut",
      tanggalLahir: "1973-10-05",
      pendidikan: "SD/Sederajat",
      pekerjaan: "Tidak Bekerja",
      penghasilan: "Dibawah 800.000",
      hp: ""
    },
    waliData: {
      statusWali: "Sama dengan ayah kandung",
      nama: "Tatang Sutisna",
      wn: "WNI",
      nik: "3205111512690001",
      hp: "0813111222",
      pendidikan: "SD/Sederajat",
      pekerjaan: "Petani/Peternak",
      penghasilan: "800.001 - 1.200.000",
      hubungan: "Ayah Kandung"
    },
    alamat: {
      ayah: {
        kepemilikan: "Milik Sendiri",
        prov: "Jawa Barat",
        kab: "Kabupaten Bandung",
        kec: "Kecamatan Kutawaringin",
        kel: "Kelurahan Jelegong",
        rt: "02",
        rw: "01",
        kodepos: "40912",
        jalan: "Kp. Babakan No. 19"
      },
      ibu: {
        samaDenganAyah: true,
        kepemilikan: "Milik Sendiri",
        prov: "Jawa Barat",
        kab: "Kabupaten Bandung",
        kec: "Kecamatan Kutawaringin",
        kel: "Kelurahan Jelegong",
        rt: "02",
        rw: "01",
        kodepos: "40912",
        jalan: "Kp. Babakan No. 19"
      },
      wali: {
        statusAlamatWali: "Sama dengan ayah kandung",
        kepemilikan: "Milik Sendiri",
        prov: "Jawa Barat",
        kab: "Kabupaten Bandung",
        kec: "Kecamatan Kutawaringin",
        kel: "Kelurahan Jelegong",
        rt: "02",
        rw: "01",
        kodepos: "40912",
        jalan: "Kp. Babakan No. 19"
      },
      domisili: {
        statusTempatTinggal: "Tinggal dengan Ayah Kandung",
        jarak: "Antara 5 - 10 KM",
        transportasi: "Angkutan Umum",
        waktuTempuh: "20 - 29 Menit"
      }
    }
  }
];

export const INITIAL_TEACHERS: Teacher[] = [
  {
    id: "tch-1",
    nipNuptk: "197508152005011003",
        nama: "Drs. H. Ahmad Fauzi",
    jk: "Laki-laki",
    tugasUtama: "Kepala Madrasah & Guru Fiqih",
    statusPegawai: "PNS",
    kategori: "Guru",
    tugasTambahan: "",
    mulaiBertugas: "2020-01-01",
    akhirBertugas: "",
    jamPelajaran: 24,
    pendidikanTerakhir: "S1",
    alamat: "",
    status: "Aktif",
    username: "guru1",
    nik: "3200000000000001",
    tempatLahir: "Jakarta",
    tanggalLahir: "1980-01-01",
    hp: "081122334455",
    email: "ahmad.fauzi@atsurmudzi.sch.id"
  },
  {
    id: "tch-2",
    nipNuptk: "198010122008012005",
        nama: "Hj. Siti Aminah, S.Pd.",
    jk: "Perempuan",
    tugasUtama: "Wakasek Kurikulum & Guru Matematika",
    statusPegawai: "PNS",
    kategori: "Guru",
    tugasTambahan: "",
    mulaiBertugas: "2020-01-01",
    akhirBertugas: "",
    jamPelajaran: 24,
    pendidikanTerakhir: "S1",
    alamat: "",
    status: "Aktif",
    username: "guru1",
    nik: "3200000000000001",
    tempatLahir: "Jakarta",
    tanggalLahir: "1980-01-01",
    hp: "081223344556",
    email: "siti.aminah@atsurmudzi.sch.id"
  },
  {
    id: "tch-3",
    nipNuptk: "198505182014021002",
        nama: "Rahmat Hidayat, S.S.",
    jk: "Laki-laki",
    tugasUtama: "Wakasek Kesiswaan & Guru Bahasa Inggris",
    statusPegawai: "PNS",
    kategori: "Guru",
    tugasTambahan: "",
    mulaiBertugas: "2020-01-01",
    akhirBertugas: "",
    jamPelajaran: 24,
    pendidikanTerakhir: "S1",
    alamat: "",
    status: "Aktif",
    username: "guru1",
    nik: "3200000000000001",
    tempatLahir: "Jakarta",
    tanggalLahir: "1980-01-01",
    hp: "085233445566",
    email: "rahmat.hidayat@atsurmudzi.sch.id"
  },
  {
    id: "tch-4",
    nipNuptk: "-",
        nama: "Deni Ramdani, S.Pd.I.",
    jk: "Laki-laki",
    tugasUtama: "Pembina OSIS & Guru Al-Qur'an Hadits",
    statusPegawai: "GTT",
    kategori: "Guru",
    tugasTambahan: "",
    mulaiBertugas: "2020-01-01",
    akhirBertugas: "",
    jamPelajaran: 24,
    pendidikanTerakhir: "S1",
    alamat: "",
    status: "Aktif",
    username: "guru2",
    nik: "3200000000000002",
    tempatLahir: "Bandung",
    tanggalLahir: "1985-02-02",
    hp: "085344556677",
    email: "deni.ramdani@atsurmudzi.sch.id"
  },
  {
    id: "tch-5",
    nipNuptk: "-",
        nama: "Eka Purwanti, S.E.",
    jk: "Perempuan",
    tugasUtama: "Bendahara Madrasah & Guru IPS",
    statusPegawai: "GTT",
    kategori: "Guru",
    tugasTambahan: "",
    mulaiBertugas: "2020-01-01",
    akhirBertugas: "",
    jamPelajaran: 24,
    pendidikanTerakhir: "S1",
    alamat: "",
    status: "Aktif",
    username: "guru2",
    nik: "3200000000000002",
    tempatLahir: "Bandung",
    tanggalLahir: "1985-02-02",
    hp: "089677889900",
    email: "eka.purwanti@atsurmudzi.sch.id"
  }
];

export const EMPTY_STUDENT = (id: string): Student => ({
  id,
  nisn: "",
  nis: "",
  nama: "",
  username: "",
  kelas: "",
  jk: "Laki-laki",
  tempatLahir: "",
  tanggalLahir: "",
  wali: "",
  status: "Aktif",
  nik: "",
  kewarganegaraan: "WNI",
  password: "",
  jumlahSaudara: "",
  anakKe: "",
  agama: "Islam",
  citaCita: "",
  hp: "",
  email: "",
  hoby: "",
  pembiaya: "Orang Tua",
  foto: "",
  ayah: {
    nama: "",
    status: "Masih Hidup",
    wn: "WNI",
    nik: "",
    tempatLahir: "",
    tanggalLahir: "",
    pendidikan: "",
    pekerjaan: "",
    penghasilan: "",
    hp: ""
  },
  ibu: {
    nama: "",
    status: "Masih Hidup",
    wn: "WNI",
    nik: "",
    tempatLahir: "",
    tanggalLahir: "",
    pendidikan: "",
    pekerjaan: "",
    penghasilan: "",
    hp: ""
  },
  waliData: {
    statusWali: "",
    nama: "",
    wn: "WNI",
    nik: "",
    hp: "",
    pendidikan: "",
    pekerjaan: "",
    penghasilan: "",
    hubungan: ""
  },
  alamat: {
    ayah: {
      kepemilikan: "",
      prov: "",
      kab: "",
      kec: "",
      kel: "",
      rt: "",
      rw: "",
      kodepos: "",
      jalan: ""
    },
    ibu: {
      samaDenganAyah: false,
      kepemilikan: "",
      prov: "",
      kab: "",
      kec: "",
      kel: "",
      rt: "",
      rw: "",
      kodepos: "",
      jalan: ""
    },
    wali: {
      statusAlamatWali: "",
      kepemilikan: "",
      prov: "",
      kab: "",
      kec: "",
      kel: "",
      rt: "",
      rw: "",
      kodepos: "",
      jalan: ""
    },
    domisili: {
      statusTempatTinggal: "",
      jarak: "",
      transportasi: "",
      waktuTempuh: ""
    }
  }
});

export const EMPTY_TEACHER = (id: string): Teacher => ({
  id,
  foto: "",
  nipNuptk: "",
  nik: "",
  nama: "",
  jk: "Laki-laki",
  tempatLahir: "",
  tanggalLahir: "",
  hp: "",
  email: "",
  username: "",
  password: "",
  statusPegawai: "",
  kategori: "Guru",
  tugasUtama: "",
  tugasTambahan: "",
  mulaiBertugas: "",
  akhirBertugas: "",
  jamPelajaran: 0,
  pendidikanTerakhir: "",
  alamat: "",
  status: "Aktif"
});
